### ISSUE TITLE
AttributeError: module 'lib' has no attribute 'SSL_CTX_set_ecdh_auto'

### ISSUE THREAD

**Issue by mweilbacher63** [peted-davis/peted-davis.github.io#1]
Getting the following error when trying to set up Pi Console:

pi@kb0fx-piconsole:~/wfpiconsole $ wfpiconsole start
[INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_22-12-22_6.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "/home/pi/.local/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.3 (default, Oct 31 2022, 14:04:00) 
[GCC 8.3.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"

  ===================================================
  Starting wfpiconsole configuration wizard          
  ===================================================

  Required fields are marked with an asterix (*)     

  API keys
  ---------------------------------
  Please enter your WeatherFlow Personal Access Token*: 87dd730f-8db6-4778-9209-1ae713968983
  Please enter your CheckWX API Key*: c62bcaf189be4a70b9afb80058
 Traceback (most recent call last):
   File "main.py", line 33, in <module>
     configFile.create()
   File "/home/pi/wfpiconsole/lib/config.py", line 97, in create
     writeConfigKey(Config, Section, Key, default[Section][Key])
   File "/home/pi/wfpiconsole/lib/config.py", line 508, in writeConfigKey
     validateAPIKeys(Config)
   File "/home/pi/wfpiconsole/lib/config.py", line 531, in validateAPIKeys
     CHECKWX = requests.get(URL, headers=header).json()
   File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
     return request('get', url, params=params, **kwargs)
   File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
     return session.request(method=method, url=url, **kwargs)
   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
     resp = self.send(prep, **send_kwargs)
   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
     r = adapter.send(request, **kwargs)
   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
     timeout=timeout
   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
     chunked=chunked)
   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
     self._validate_conn(conn)
   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 841, in _validate_conn
     conn.connect()
   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 332, in connect
     cert_reqs=resolve_cert_reqs(self.cert_reqs),
   File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 264, in create_urllib3_context
     context = SSLContext(ssl_version or ssl.PROTOCOL_SSLv23)
   File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 391, in __init__
     self._ctx = OpenSSL.SSL.Context(self.protocol)
   File "/home/pi/.local/lib/python3.7/site-packages/OpenSSL/SSL.py", line 674, in __init__
     res = _lib.SSL_CTX_set_ecdh_auto(context, 1)
 AttributeError: module 'lib' has no attribute 'SSL_CTX_set_ecdh_auto'

**Comment by peted-davis** [comment]
Thanks for the bug report. I will have a look into it
